from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [ 
    path('cart',views.show_cart,name='cart'),#route to cart view, when the user accesses the /cart URL of the application then this view function will be called and it will render the cart.html template which is located in templates folder as we have specified the template directory in settings.py as BASE_DIR / 'templates'
    path('orders',views.show_orders,name='orders'),#route to orders view, when the user accesses the /orders URL of the application then this view function will be called and it will render the orders.html template which is located in templates folder as we have specified the template directory in settings.py as BASE_DIR / 'templates'
    
    path('add_to_cart',views.add_to_cart,name='add_to_cart'),#route to add to cart view, when the user clicks on the add to cart button in the product detail page of the application then this view function will be called and it will add the product with the given primary key (pk) to the cart of the user and redirect them to the cart page of the application, we can use this add_to_cart view function to add the products to the cart of the user when they click on the add to cart button in the product detail page of the application
    path('remove_from_cart/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),#route to remove from cart view, when the user clicks on the remove button in the cart page of the application then this view function will be called and it will remove the product with the given primary key (pk) from the cart of the user and redirect them to the cart page of the application, we can use this remove_from_cart view function to remove the products from the cart of the user when they click on the remove button in the cart page of the application
    path('checkout',views.checkout_cart,name='checkout')#route to checkout cart view, when the user clicks on the checkout button in the cart page of the application then this view function will be called and it will change the order status of the cart of the user to ORDER_CONFIRMED and redirect them to the account page of the application, we can use this checkout_cart view function to change the order status of the cart of the user to ORDER_CONFIRMED and redirect them to the account page of the application when they click on the checkout button in the cart page of the application
]