# Generated by Django 6.0.2 on 2026-02-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='media/site/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
