# Generated by Django 6.0.2 on 2026-03-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
