# Generated by Django 6.0.2 on 2026-03-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordereditem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='size',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
